### ISSUE TITLE
flash_attn安装

### ISSUE THREAD

**Issue by Jwzddd** [Spico197/Humback#5]
请问falsh_attn包是必须的么，我在安装它的时候遇到了很多头疼的问题，尝试注释掉之后又遇到了很多新的错误。

**Comment by Spico197** [comment]
嗨您好，感谢对本项目的关注。
可以不用flash-attn，只是训练会变慢，显存占用也会更多。只要把`src.core.train_flash_attn`改为`src.core.train`即可。

https://github.com/Spico197/Humback/blob/641153764e59bd4443a2c42b893c9fec6db24467/scripts/train_seed.sh#L20-L24

**Comment by Jwzddd** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Jwzddd** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。   您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
